### ISSUE TITLE
Where is the VIDD metrics 

### ISSUE THREAD

**Issue by zihaozou** [ziyannchen/VFRxBenchmark#1]
Hi,

appreciate your work!

I am looking for the VIDD metric, but I could not find it.

Where could I find the VIDD metric?

**Comment by ziyannchen** [comment]
Thx for reaching out.
VIDD is encapsulated in [cos_dist_metric.py](https://github.com/ziyannchen/VFRxBenchmark/blob/f3508d8578116c1baca5a63428a994a72aa2ae39/bfrxlib/metrics/cos_dist_metric.py#L107).
